INSERT INTO CUSTOMER (ID, CUST_NAME, CUST_ADDRESS, CUST_JOB) VALUES (1, 'John', 'Quezon City', 'BACKEND')
INSERT INTO CUSTOMER (ID, CUST_NAME, CUST_ADDRESS, CUST_JOB) VALUES (2, 'Mark', 'Muntinlupa City', 'FRONTEND')
INSERT INTO CUSTOMER (ID, CUST_NAME, CUST_ADDRESS, CUST_JOB) VALUES (3, 'Paul', 'Manila City', 'DEVOPS')



