INSERT INTO EMPLOYEE (ID, EMP_NAME, EMP_ADDRESS, EMP_JOB) VALUES (1, 'John', 'Quezon City', 'BACKEND')
INSERT INTO EMPLOYEE (ID, EMP_NAME, EMP_ADDRESS, EMP_JOB) VALUES (2, 'Mark', 'Muntinlupa City', 'FRONTEND')
INSERT INTO EMPLOYEE (ID, EMP_NAME, EMP_ADDRESS, EMP_JOB) VALUES (3, 'Paul', 'Manila City', 'DEVOPS')



