INSERT INTO JOB (JOB_ID, JOB_DESC, JOB_POS) VALUES (1, 'BACKEND', 'JUNIOR')
INSERT INTO JOB (JOB_ID, JOB_DESC, JOB_POS) VALUES (2, 'BACKEND', 'MID')
INSERT INTO JOB (JOB_ID, JOB_DESC, JOB_POS) VALUES (3, 'BACKEND', 'SENIOR')



INSERT INTO EMPLOYEE (ID, EMP_NAME, EMP_ADDRESS, EMP_JOB_ID) VALUES (1, 'John', 'Quezon City', 1 )
INSERT INTO EMPLOYEE (ID, EMP_NAME, EMP_ADDRESS, EMP_JOB_ID) VALUES (2, 'Mark', 'Muntinlupa City', 2)
INSERT INTO EMPLOYEE (ID, EMP_NAME, EMP_ADDRESS, EMP_JOB_ID) VALUES (3, 'Paul', 'Manila City', 3)



